- name: List ssh services
  ansible.builtin.shell: systemctl list-units --type=service ssh* --output json
  register: ssh_service
  changed_when: false
  tags:
    - skip_ansible_lint
  check_mode: false

- name: SSH service name initial value
  ansible.builtin.set_fact:
    ssh_service_name: null

- name: Set ssh service name
  ansible.builtin.set_fact:
    ssh_service_name: "{{
      item
      if (ssh_service.stdout | from_json | json_query('[?contains(unit, `' + item + '`)] | [0].unit')) != None
      else ssh_service_name }}"
  loop:
    - ssh.service
    - sshd.service

# - name: Test
#   ansible.builtin.debug:
#     msg:
#       - "{{ ssh_service_name }}"
#       - "{{ ssh_service }}"

- name: Make sure sshd service is started and enabled
  become: true
  ansible.builtin.systemd_service:
    name: "{{ ssh_service_name }}"
    enabled: true
    state: started

# dont use sshd socket, so we can use multiple ports in sshd_config
# ref: https://askubuntu.com/questions/1439461/ssh-default-port-not-changing-ubuntu-22-10
- name: Make sure sshd socket is stopped and disabled
  become: true
  ansible.builtin.systemd_service:
    name: "{{ ssh_service_name | replace('.service', '.socket') }}"
    enabled: false
    state: stopped
  ignore_errors: true
  register: disable_sshd_socket

- name: Fail if no ssh service found
  ansible.builtin.fail:
    msg: "No SSH service found in systemd!"
  when: ssh_service_name == None
